version: '3'

services:
  missioncontrol:
    build: .
    command: 'nodemon --inspect=0.0.0.0:9229 server/start-servers.js'
    ports:
      - '8888:8443'
      - '9090:9090'
      - '5858:5858'
      - '9229:9229'
    environment:
      NODE_ENV: development
      DAV_ENV: simulated
      WEB_SERVER_PORT: 8443
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AEROSPIKE_HOST: aerospike
      ELEVATION_API_KEY: AIzaSyBzNsELkqXiZBlMzEB68rX_JwY5Q9CtPys
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - redis:redis
      - aerospike:aerospike
    networks:
      - dav
  redis:
    image: redis
    networks:
      - dav
  aerospike:
    image: aerospike/aerospike-server
    environment:
      NAMESPACE: mission_control
    networks:
      - dav
    ports:
      - '3000:3000'
networks:
  dav:
    external: true
