name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: "11.x"

      - name: Install
        run: |
          npm i

      - name: Test
        run: |
          make tslint tsc jest

      - name: Build
        run: |
          make build-ci
