name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        run: |
          npm i

      - name: Test
        run: |
          make tslint tsc jest

      - name: Build
        run: |
          make build
