name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run a multi-line script
        run: |
          make tslint tsc jest
          make build
          echo 'Done'
